"""empty message

Revision ID: 42b504dba42b
Revises: ac90ae58cab0
Create Date: 2025-01-10 15:57:09.713228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '42b504dba42b'
down_revision = 'ac90ae58cab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('important_questions',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('important_questions',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
